import jsPDF from 'jspdf';
import 'jspdf-autotable';

/**
 * Export a flashcard/test session to PDF.
 */
export function exportSessionPDF({ results, profileName, categories }) {
  const doc = new jsPDF();
  const total = results.correct.length + results.missed.length + results.skipped.length;
  const score = total > 0 ? Math.round((results.correct.length / total) * 100) : 0;
  const date = new Date().toLocaleDateString('en-GB');

  // Header
  doc.setFontSize(22);
  doc.setTextColor(15, 23, 42);
  doc.text('RE-VISION', 14, 20);
  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);
  doc.text(`${profileName} | ${date}`, 14, 28);

  // Summary
  doc.setFontSize(14);
  doc.setTextColor(15, 23, 42);
  doc.text('Session Summary', 14, 40);

  doc.setFontSize(11);
  doc.text(`Score: ${score}%`, 14, 50);
  doc.text(`Correct: ${results.correct.length} | Missed: ${results.missed.length} | Skipped: ${results.skipped.length}`, 14, 57);
  doc.text(`Total Questions: ${total}`, 14, 64);

  if (results.totalTimeMs) {
    const seconds = Math.round(results.totalTimeMs / 1000);
    const mins = Math.floor(seconds / 60);
    const secs = seconds % 60;
    doc.text(`Time: ${mins}m ${secs}s`, 14, 71);
  }

  // Questions table
  const allCards = [
    ...results.correct.map(c => ({ ...c, result: 'Correct' })),
    ...results.missed.map(c => ({ ...c, result: 'Missed' })),
    ...results.skipped.map(c => ({ ...c, result: c.timedOut ? 'Timed Out' : 'Skipped' }))
  ];

  const tableData = allCards.map((card, i) => [
    i + 1,
    card.question?.length > 60 ? card.question.substring(0, 57) + '...' : card.question,
    card.category || '',
    card.result,
    card.timeSpentMs ? `${Math.round(card.timeSpentMs / 1000)}s` : '-'
  ]);

  doc.autoTable({
    startY: results.totalTimeMs ? 80 : 73,
    head: [['#', 'Question', 'Category', 'Result', 'Time']],
    body: tableData,
    styles: { fontSize: 8, cellPadding: 2 },
    headStyles: { fillColor: [59, 130, 246], textColor: [255, 255, 255] },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    columnStyles: {
      0: { cellWidth: 10 },
      1: { cellWidth: 85 },
      2: { cellWidth: 35 },
      3: { cellWidth: 20 },
      4: { cellWidth: 15 }
    }
  });

  // Footer
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text('Generated by RE-VISION', 14, doc.internal.pageSize.height - 10);
  }

  doc.save(`re-vision-session-${date.replace(/\//g, '-')}.pdf`);
}

/**
 * Export a progress report to PDF.
 */
export function exportProgressPDF({ stats, profileName }) {
  const doc = new jsPDF();
  const date = new Date().toLocaleDateString('en-GB');

  // Header
  doc.setFontSize(22);
  doc.setTextColor(15, 23, 42);
  doc.text('RE-VISION', 14, 20);
  doc.setFontSize(12);
  doc.setTextColor(100, 116, 139);
  doc.text(`Progress Report - ${profileName}`, 14, 28);
  doc.setFontSize(10);
  doc.text(`Generated: ${date}`, 14, 35);

  // Stats summary
  doc.setFontSize(14);
  doc.setTextColor(15, 23, 42);
  doc.text('Overview', 14, 48);

  doc.setFontSize(11);
  doc.text(`Current Streak: ${stats?.currentStreak || 0} days`, 14, 58);
  doc.text(`Longest Streak: ${stats?.longestStreak || 0} days`, 14, 65);
  doc.text(`Total Cards Studied: ${stats?.totalCardsStudied || 0}`, 14, 72);
  doc.text(`Overall Accuracy: ${stats?.overallAccuracy || 0}%`, 14, 79);
  doc.text(`Total Sessions: ${stats?.totalSessions || 0}`, 14, 86);

  // Category breakdown
  if (stats?.categoryBreakdown?.length > 0) {
    doc.setFontSize(14);
    doc.text('Category Breakdown', 14, 100);

    const categoryData = stats.categoryBreakdown.map(c => [
      c.category,
      c.cardCount,
      `${c.correct}/${c.total}`,
      `${c.accuracy}%`,
      c.accuracy >= 80 ? 'Strong' : c.accuracy >= 60 ? 'Moderate' : 'Needs Work'
    ]);

    doc.autoTable({
      startY: 105,
      head: [['Category', 'Cards', 'Correct/Total', 'Accuracy', 'Strength']],
      body: categoryData,
      styles: { fontSize: 9, cellPadding: 3 },
      headStyles: { fillColor: [59, 130, 246], textColor: [255, 255, 255] },
      alternateRowStyles: { fillColor: [248, 250, 252] }
    });
  }

  // Weakest areas
  if (stats?.weakestCards?.length > 0) {
    const currentY = doc.lastAutoTable ? doc.lastAutoTable.finalY + 15 : 130;
    doc.setFontSize(14);
    doc.text('Areas for Improvement', 14, currentY);

    const weakData = stats.weakestCards.slice(0, 5).map(c => [
      c.question?.length > 50 ? c.question.substring(0, 47) + '...' : c.question,
      c.category,
      `${c.incorrectCount}x missed`
    ]);

    doc.autoTable({
      startY: currentY + 5,
      head: [['Question', 'Category', 'Status']],
      body: weakData,
      styles: { fontSize: 9, cellPadding: 3 },
      headStyles: { fillColor: [239, 68, 68], textColor: [255, 255, 255] },
      alternateRowStyles: { fillColor: [248, 250, 252] }
    });
  }

  // Footer
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text('Generated by RE-VISION', 14, doc.internal.pageSize.height - 10);
  }

  doc.save(`re-vision-progress-${profileName}-${date.replace(/\//g, '-')}.pdf`);
}

/**
 * Export PDF button component
 */
export default function ExportPDFButton({ onClick, label = 'Export PDF' }) {
  return (
    <button
      onClick={onClick}
      className="px-4 py-2 bg-slate-700 hover:bg-slate-600 text-white text-sm font-medium rounded-lg transition-colors flex items-center space-x-2"
    >
      <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
        <path strokeLinecap="round" strokeLinejoin="round" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
      </svg>
      <span>{label}</span>
    </button>
  );
}
